version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: brainbolt_mongo
    ports:
      - "27017:27017"
    # volumes:
    #   - ./data/mongo:/data/db
    restart: always

  redis:
    image: redis:alpine
    container_name: brainbolt_redis
    ports:
      - "6379:6379"
    # volumes:
    #   - ./data/redis:/data
    restart: always
